
version: '3'

services:
  apache2:
    build: ./apache2
    ports:
      - "${APACHE_PORT}:80"
    environment:
      - XDEBUG_CONFIG="remote_host=192.168.22.1"
    volumes:
      - ./apache2/sites:/etc/apache2/sites-available
      - ./apache2/php.ini:/usr/local/etc/php/php.ini
      - ${APPLICATION}:/var/www/html

  mysql:
    build: ./mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
