
version: '3'

services:
  apache2:
    build: ./apache2
    ports:
      - "80:80"
    volumes:
      - ./apache2/sites:/etc/apache2/sites-available
      - ./apache2/php.ini:/usr/local/etc/php/php.ini
      - /home/vagrant/sites:/var/www/html

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - /home/vagrant/shared/mysql:/var/lib/mysql
